/**
 * Created by zppro on 17-8-1.
 */

export const indexTypes = {
  SET_API_TOKEN: 'SET_API_TOKEN',
  SET_API_TOKEN_TS: 'SET_API_TOKEN_TS',
  SET_$KEYS: 'SET_$KEYS',
  SET_CITY: 'SET_CITY',
  SET_CITIES: 'SET_CITIES'
}

export const tpaTypes = {
  SET_STATS: 'SET_STATS',
  SET_SEARCH_DIMENSIONS: 'SET_SEARCH_DIMENSIONS',
  SET_SLIDERS: 'SET_SLIDERS',
  SET_TABS: 'SET_TABS',
  SET_TAB_AGENCIES: 'SET_TAB_AGENCIES',
  SET_AGENCIES: 'SET_AGENCIES',
  SET_CURRENT_AGENCY: 'SET_CURRENT_AGENCY'
}

export const uaTypes = {
  SET_USER: 'SET_USER',
  SET_TOKEN: 'SET_TOKEN',
  SET_AUTH_RETURN_URL: 'SET_AUTH_RETURN_URL',
  CLEAR_USER_TOKEN: 'CLEAR_USER_TOKEN'
}