/**
 * Created by zppro on 17-8-1.
 */

export const indexTypes = {
  SET_$KEYS: 'SET_$KEYS',
  SET_CITY: 'SET_CITY',
  SET_CITIES: 'SET_CITIES'
}

export const tpaTypes = {
  SET_STATS: 'SET_STATS',
  SET_SEARCH_DIMENSIONS: 'SET_SEARCH_DIMENSIONS',
  SET_SLIDERS: 'SET_SLIDERS',
  SET_TABS: 'SET_TABS',
  SET_TAB_AGENCIES: 'SET_TAB_AGENCIES',
  SET_AGENCIES: 'SET_AGENCIES',
  SET_CURRENT_AGENCY: 'SET_CURRENT_AGENCY'
}